global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: "pandemies_api"
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8000"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "node_exporter"
    static_configs:
      # si node-exporter est en host network, scrappe l'hôte
      - targets: ["localhost:9100"]


