name: CI - Pandémies

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: "3.12"
  # IMPORTANT: on dit au runner de ne PAS télécharger les blobs LFS
  GIT_LFS_SKIP_SMUDGE: "1"

jobs:
  test:
    name: Install + Pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (skip LFS blobs)
        uses: actions/checkout@v4
        with:
          lfs: false   # on garde LFS dans le repo, mais on ne télécharge pas les fichiers

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-${{ env.PYTHON_VERSION }}-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      # >>> ICI: on crée un modèle factice à l'endroit EXACT attendu par l'API
      - name: Prepare dummy model for CI (no LFS download)
        run: |
          python - << 'PY'
          from pathlib import Path
          import numpy as np
          from joblib import dump
          from sklearn.dummy import DummyRegressor
          from prediction.config import MODEL_PATH
          p = Path(MODEL_PATH)
          p.parent.mkdir(parents=True, exist_ok=True)
          m = DummyRegressor(strategy="mean")
          m.fit(np.array([[0]]), np.array([0.0]))
          dump(m, p)
          print("Dummy model written to:", p)
          PY

      - name: Run tests
        run: pytest -q

  docker-build:
    name: Docker build (API & App)
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (skip LFS blobs)
        uses: actions/checkout@v4
        with:
          lfs: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build API image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile.api
          push: false
          tags: ci-local/api:${{ github.sha }}

      - name: Build App image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile.app
          push: false
          tags: ci-local/app:${{ github.sha }}
